const fs = require('fs');
const path = require('path');
const mongoose = require('mongoose');
const crypto = require('crypto');
// REQUIRE the 'xlsx' package for direct Excel file reading
const XLSX = require('xlsx');

// --- 1. CONFIGURATION AND UTILITIES ---

// Import Mongoose Models (assuming correct relative path to app/models)
const { N8nJobResponse_CustomAiDB } = require('../../app/models/N8nJobResponse');
const { N8nWorkflowJob_CustomAiDB } = require('../../app/models/N8nWorkflowJob');

// The required path to the XLSX file.
// You must place your 'Custom AI Bot.xlsx' file in this directory.
const XLSX_FILE_PATH = path.join(__dirname, 'Custom AI Bot.xlsx');

/**
 * Mocks the process of generating a unique GridFS file ID, which is a standard MongoDB ObjectId.
 * This is used for the fields that are designed to hold file references (generatedCodeFileId, balanceSketchFileId).
 */
function createFakeFileId() {
    return new mongoose.Types.ObjectId();
}

/**
 * XLSX parsing function using the 'xlsx' library.
 * Reads the first sheet of the file and converts it into an array of JSON objects.
 * This version forces reading the entire used range of the sheet.
 *
 * @param {string} filePath - The path to the XLSX file.
 * @returns {Array<Object>} Array of parsed records.
 */
function parseXlsx(filePath) {
    if (!fs.existsSync(filePath)) {
        throw new Error(`XLSX file not found at path: ${filePath}`);
    }

    const workbook = XLSX.readFile(filePath);
    const sheetName = workbook.SheetNames[0];
    const worksheet = workbook.Sheets[sheetName];

    // --- FIX: Force reading the entire range to catch all rows ---
    // 1. Get the current defined range (e.g., "A1:Z85").
    const range = worksheet['!ref'];
    if (!range) {
        throw new Error("Worksheet range could not be determined. The sheet may be empty or improperly formatted.");
    }

    // 2. Decode the range to find the last column (e.g., Z) and the last row (e.g., 85).
    const decodedRange = XLSX.utils.decode_range(range);

    // 3. Manually extend the range to a high number (e.g., 2000) to ensure ALL data is captured,
    //    while keeping the original last column. This forces the parser to process the full area.
    const lastCol = XLSX.utils.encode_col(decodedRange.e.c);
    const forcedRange = `A1:${lastCol}${Math.max(2000, decodedRange.e.r + 1)}`;

    console.log(`[XLSX Parser] Original Range: ${range}. Using Forced Range: ${forcedRange}`);


    // Convert the worksheet data to a JSON array of objects using the forced range.
    const jsonRecords = XLSX.utils.sheet_to_json(worksheet, {
        header: 1,
        defval: "", // Treat empty cells as empty strings
        range: forcedRange, // Use the forced range to read more rows
    });

    if (jsonRecords.length < 2) {
        return [];
    }

    // Process headers and data for consistent key mapping
    const headers = jsonRecords[0].map(h => String(h).trim());
    const data = jsonRecords.slice(1);

    const records = data.map(row => {
        const record = {};
        headers.forEach((header, index) => {
            record[header] = row[index];
        });
        return record;
    }).filter(record =>
        // Filter out completely empty rows which can sometimes be generated by Excel exports
        Object.values(record).some(value => String(value).trim() !== '')
    );

    console.log(`[XLSX Parser] Successfully read and filtered ${records.length} records.`);
    return records;
}

/**
 * Cleans up large string fields from surrounding markdown/backticks often found in spreadsheet exports.
 * This handles the ```svg\n<svg...></svg>\n``` format seen in the n8n data.
 *
 * @param {string} rawString - The string to clean.
 * @returns {string} The cleaned string.
 */
function cleanLargeString(rawString) {
    if (!rawString) return '';
    let cleaned = String(rawString).trim();

    // Check for and remove surrounding triple backticks (e.g., ```svg\n content \n```)
    if (cleaned.startsWith('```') && cleaned.endsWith('```')) {
        // Find the index of the first newline after the opening ``` (which might contain the language name)
        const firstNewline = cleaned.indexOf('\n');

        if (firstNewline !== -1) {
            // Remove the opening triple backticks and everything up to the first newline
            cleaned = cleaned.substring(firstNewline + 1);
        } else {
            // Handle case where ``` is on the same line as content
            cleaned = cleaned.substring(3);
        }

        // Remove the closing ```
        cleaned = cleaned.substring(0, cleaned.lastIndexOf('```')).trim();
    }

    // Replace common escaped characters that interfere with code/SVG
    cleaned = cleaned.replace(/\\"/g, '"');

    return cleaned;
}

/**
 * The data mapper function to transform a single XLSX record into the Mongoose schema shape.
 * It maps ALL fields and handles data type conversions and cleaning.
 *
 * @param {Object} record - A single parsed XLSX row.
 * @returns {{jobResponse: Object, workflowJob: Object}} The mapped document payloads.
 */
function mapDataToSchema(record) {
    // 1. Data Type Conversions and Cleaning
    let tradeLog;
    let signalDistribution;

    // --- FIX: Explicitly map Debug Log and Trade Log to their correct columns ---
    const rawDebugLog = String(record['Debug Log'] || record.DebugLog || '').trim();
    const tradeLogContent = record['Backtest Log'] || record.BacktestLog;

    const avgDuration = String(record['Avg. Trade Duration'] || record.AvgTradeDuration || '').trim();

    try {
        const logString = String(tradeLogContent || '[]').trim();

        // Handle "N/A", empty, or strings that are clearly not JSON arrays (Debug Log content).
        if (logString.toUpperCase() === 'N/A' || logString === '' || logString === '[]' || logString.startsWith('K') || logString.startsWith('C')) {
            tradeLog = [];
        } else {
            // Replace single quotes with double quotes for valid JSON parsing
            tradeLog = JSON.parse(logString.replace(/'/g, '"'));
        }
        if (!Array.isArray(tradeLog)) throw new Error('Parsed log is not an array.');

    } catch (e) {
        console.warn(`[Warning] Failed to parse Trade Log for Req ID ${record['Request ID']}. Defaulting to []. Error: ${e.message}`);
        tradeLog = [];
    }

    try {
        const distributionContent = record['Signal Distribution'] || record.SignalDistribution;
        signalDistribution = distributionContent ? JSON.parse(String(distributionContent).replace(/'/g, '"')) : {};
    } catch (e) {
        console.warn(`[Warning] Failed to parse Signal Distribution for Req ID ${record['Request ID']}. Defaulting to {}. Error: ${e.message}`);
        signalDistribution = {};
    }

    // 2. Process Raw Code and SVG
    const rawGeneratedCode = cleanLargeString(record.GeneratedCode);
    const rawBalanceSketch = cleanLargeString(record['Balance Sketch']);

    // 3. Generate fake ObjectIds for GridFS references (required by schema)
    const generatedCodeFileId = createFakeFileId();
    const balanceSketchFileId = createFakeFileId();

    // 4. Generate a pseudo-user ID for the job
    const userId = crypto.randomUUID().replace(/-/g, '').substring(0, 24);

    const n8nJobResponsePayload = {
        // Top-Level Response Metadata (Timestamp is handled by Mongoose `timestamps: true`)
        status: record.Status,
        requestID: record['Request ID'],
        attempt: parseInt(record.Attempts, 10) || 1,

        // --- Mapped Missing Fields (Assuming future/flexible schema updates) ---
        modelUsed: record.ModelUsed,
        feedback: record.Feedback,

        // Original Input
        input: {
            originalPrompt: record.OriginalPrompt,
            cleanedPrompt: record.OriginalPrompt, // Using original for lack of distinct cleaned prompt in XLSX
            experienceLevel: record['Experience Level'],
            backtestSymbol: record.Symbol,
            backtestInterval: record.Timeframe,
        },

        // Generated Code & Summary
        generatedCode: {
            summary: {
                overview: record.Overview,
                executionLogic: record.ExecutionLogic,
                longEntryCondition: record.LongEntryCondition,
                shortEntryCondition: record.ShortEntryCondition,
                otherConditions: record.ExitCondition || 'N/A',
            },
            // Existing ObjectId field (Required by schema)
            generatedCodeFileId: generatedCodeFileId,
            // Flexible field to hold the full code string
            fullCode: rawGeneratedCode,
        },

        // Backtest Results
        backtest: {
            status: record.Status,
            errorMessage: record.Status === 'Success' ? null : 'Backtest failed based on XLSX status.',
            roi: record['ROI %'],
            winRatio: record['Win Ratio'],
            simulatedTrades: parseInt(record.Trades, 10) || 0,
            profitFactor: record['Profit Factor'],
            sharpeRatio: record['Sharpe Ratio'],
            sortinoRatio: record['Sortino Ratio'],
            maxDrawdown: record['Max. Drawdown'],
            avgTradePnL: record['Avg. Trade PnL'],
            avgDuration: avgDuration, // Cleaned duration string
            exposureTime: record.ExposureTime,

            // Log/Distribution Fields
            tradeLog: tradeLog, // This is the cleaned JSON array
            signalDistribution: signalDistribution,
            debugLog: rawDebugLog, // This is the raw string from the debug log column

            // Existing ObjectId field (Required by schema)
            balanceSketchFileId: balanceSketchFileId,
            // Flexible field for the full SVG string
            fullBalanceSketch: rawBalanceSketch,
        }
    };

    const n8nWorkflowJobPayload = {
        userId: new mongoose.Types.ObjectId(userId),
        type: 'ai-model',
        status: record.Status === 'Success' ? 'completed' : 'failed',
        webhookPath: `/n8n/webhook/${record['Request ID']}`,
        requestPayload: {
            originalPrompt: record.OriginalPrompt,
            symbol: record.Symbol,
            timeframe: record.Timeframe,
            experienceLevel: record['Experience Level'],
        },
        responsePayload: null, // Defer to N8nJobResponse
        error: record.Status === 'Success' ? null : 'Workflow failure.',
    };

    return { jobResponse: n8nJobResponsePayload, workflowJob: n8nWorkflowJobPayload };
}


// --- 2. THE SEEDER MAIN FUNCTION ---

async function seedN8nData() {
    console.log('--- Starting N8n Data Seeder (Full Import) ---');

    let rawRecords;
    try {
        // Use the dedicated XLSX parser to read all records from the first sheet
        rawRecords = parseXlsx(XLSX_FILE_PATH);
    } catch (error) {
        console.error(`[FATAL] Could not process XLSX file at ${XLSX_FILE_PATH}.`);
        console.error('Please ensure the file exists and npm install xlsx has been run.');
        console.error('Error details:', error.message);
        return;
    }

    if (rawRecords.length === 0) {
        console.log('No data records found to seed after parsing the XLSX file.');
        return;
    }

    try {
        console.log(`Processing ${rawRecords.length} records...`);

        // Clear previous data for a clean seed run
        await N8nWorkflowJob_CustomAiDB.deleteMany({});
        await N8nJobResponse_CustomAiDB.deleteMany({});
        console.log('Cleaned existing N8nJob and N8nJobResponse collections.');

        for (const record of rawRecords) {

            // 1. Map data to the two schema payloads, including all fields and clean SVG/Code
            const { jobResponse, workflowJob } = mapDataToSchema(record);

            // 2. Create the detailed response document INSTANCE (Child)
            const jobResponseDoc = new N8nJobResponse_CustomAiDB(jobResponse);

            // 3. Create the parent workflow job and save it to get its _id
            const workflowJobDoc = new N8nWorkflowJob_CustomAiDB(workflowJob);
            await workflowJobDoc.save();

            // 4. NOW that we have the parent ID, assign it to the child document
            jobResponseDoc.jobId = workflowJobDoc._id;

            // 5. Link the parent job to the response document
            workflowJobDoc.response = jobResponseDoc._id;
            // Use updateOne to link the response ID back to the job document
            await N8nWorkflowJob_CustomAiDB.updateOne(
                { _id: workflowJobDoc._id },
                { $set: { response: jobResponseDoc._id } }
            );

            // 6. Save the child document (N8nJobResponse) with the now-required jobId field populated
            await jobResponseDoc.save();

            console.log(`\tSeeded Job: ${workflowJobDoc._id} (Req ID: ${record['Request ID']})`);
        }

        console.log('Seeding completed successfully.');
    } catch (err) {
        console.error('An error occurred during seeding:', err);
        // Important: Re-throw error to ensure the runner/main script catches it
        throw err;
    } finally {
        console.log('Seeder process finished.');
    }
}

module.exports = { seedN8nData };
