'use client';

import React, { useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {addToast} from "@heroui/react";

import Combobox from "@/components/shared/ui/Combobox";
import {DropdownOption} from "@/types/ui/DropdownOption";
import {GeneratedStrategy, StrategyReport} from "@/types/AIStrategy";

// =====================================================================
// --- MOCK DATA & API SIMULATION ---
// =====================================================================

const AI_MODELS: DropdownOption[] = [
    { name: 'Chat-GPT 5', logo: 'https://img.icons8.com/?size=100&id=FBO05Dys9QCg&format=png&color=C1C1C1' },
    { name: 'Gemini 2.5 Pro', logo: 'https://img.icons8.com/?size=100&id=iBkBIBWE6tfT&format=png&color=000000' },
    { name: 'Grok 4', logo: 'https://img.icons8.com/?size=100&id=USGXKHXKl9X7&format=png&color=C1C1C1' },
];

const OUTPUT_TABS = ['Strategy Code', 'Conditions Report'];

const simulateAIGeneration = async (prompt: string, model: string): Promise<GeneratedStrategy> => {
    await new Promise(resolve => setTimeout(resolve, 2500));

    return {
        code: `// Strategy generated by ${model}\n//@version=5\nstrategy("AI Optimized Crossover Strategy", overlay=true)\n\n// Inputs\nemaFast = input.int(50, title="Fast EMA")\nemaSlow = input.int(200, title="Slow EMA")\nrsiLen = input.int(14, title="RSI Length")\n\n// Calculations\nfastMA = ta.ema(close, emaFast)\nslowMA = ta.ema(close, emaSlow)\nrsi = ta.rsi(close, rsiLen)\n\n// Conditions\nlongCondition = ta.crossover(fastMA, slowMA) and rsi > 50\nshortCondition = ta.crossunder(fastMA, slowMA) and rsi < 50\n\n// Execute Trades\nif (longCondition)\n    strategy.entry("Long", strategy.long)\n    strategy.close("Short")\n\nif (shortCondition)\n    strategy.entry("Short", strategy.short)\n    strategy.close("Long")`,
        report: {
            overview: "This strategy is designed to operate in trending markets, identifying both bullish and bearish shifts. It uses a dual moving average crossover system to determine the primary trend direction, confirmed by an oscillator to gauge momentum before entering a trade.",
            strategy: [
                { component: 'Long Entry', indicator: 'EMA 50/200 Crossover (Golden Cross) & RSI > 50' },
                { component: 'Short Entry', indicator: 'EMA 50/200 Crossunder (Death Cross) & RSI < 50' },
                { component: 'Volume Analysis', indicator: 'Price should respect the Volume Weighted Average Price (VWAP)' },
                { component: 'Exit Condition', indicator: 'An opposite crossover signal triggers an exit and potential reversal' },
            ],
            execution: "For a long position, the strategy waits for the 50-period EMA to cross above the 200-period EMA and confirms with an RSI above 50. For a short position, it waits for the 50-period EMA to cross below the 200-period EMA, confirmed by an RSI below 50. Each new signal closes the preceding trade."
        },
        metadata: { name: `AI_Strategy_${Date.now()}` }
    };
};

const simulateBacktest = async (code: string) => {
    addToast({
        title: `Backtesting Started with code: ${code.substring(0, 10)}...`,
        description: 'Your strategy is being tested against the historical data. This may take a few minutes.',
        color: 'warning'
    })
    await new Promise(resolve => setTimeout(resolve, 1500));
    const winRatio = Math.random() * (0.85 - 0.55) + 0.55;

    return { winRatio, totalTrades: 150, profitFactor: 1.85 };
};

// =====================================================================
// --- REUSABLE SUB-COMPONENTS ---
// =====================================================================

const Spinner: React.FC<{ className?: string }> = ({ className = "h-5 w-5" }) => (
    <svg className={`animate-spin text-white ${className}`} fill="none" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
        <path className="opacity-75" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" fill="currentColor" />
    </svg>
);

const SkeletonLoader = () => (
    <div className="animate-pulse pt-3">
        <div className="flex space-x-6 mb-4">
            <div className="h-4 w-32 bg-gray-700/50 rounded" />
            <div className="h-4 w-32 bg-gray-700/50 rounded" />
        </div>
        <div className="space-y-3 p-4 bg-dark-gray rounded-md border border-gray-600 h-[400px]">
            <div className="h-3 bg-gray-700/50 rounded w-3/4" />
            <div className="h-3 bg-gray-700/50 rounded" />
            <div className="h-3 bg-gray-700/50 rounded w-1/2" />
        </div>
        <div className="flex justify-between items-start pt-4 mt-[-15px]">
            <div className="h-10 w-20 bg-gray-700/50 rounded-full" />
            <div className="flex space-x-4">
                <div className="h-10 w-32 bg-gray-700/50 rounded-full" />
                <div className="h-10 w-32 bg-gray-700/50 rounded-full" />
            </div>
        </div>
    </div>
);

const ResultTabs: React.FC<{ tabs: string[]; activeTab: string; setActiveTab: (tab: string) => void }> = ({ tabs, activeTab, setActiveTab }) => (
    <div className="flex space-x-6">
        {tabs.map(tab => (
            <button
                key={tab}
                className={`${activeTab === tab ? 'text-white' : 'text-gray-500 hover:text-gray-200'} relative py-2 text-sm font-medium transition-colors duration-300 focus:outline-none`}
                onClick={() => setActiveTab(tab)}
            >
                {tab}
                {activeTab === tab && (
                    <motion.div
                        className="absolute bottom-0 left-0 right-0 h-[2px] bg-white"
                        layoutId="activeResultTabUnderline"
                        transition={{ type: 'spring', stiffness: 350, damping: 30 }}
                    />
                )}
            </button>
        ))}
    </div>
);

const WinRatioGauge: React.FC<{ ratio: number }> = ({ ratio }) => {
    const percentage = Math.round(ratio * 100);
    const radius = 40;
    const circumference = 2 * Math.PI * radius;
    const strokeDashoffset = circumference - (ratio * circumference);
    const colorClass = percentage >= 65 ? 'text-green-500' : percentage >= 50 ? 'text-yellow-500' : 'text-red-500';

    return (
        <div className="flex items-center space-x-3">
            <div className="relative w-20 h-20">
                <svg className="w-full h-full transform -rotate-90" viewBox="0 0 100 100">
                    <circle className="text-gray-800" cx="50" cy="50" fill="transparent" r={radius} stroke="currentColor" strokeWidth="8" />
                    <motion.circle
                        animate={{ strokeDashoffset }}
                        className={colorClass}
                        cx="50"
                        cy="50"
                        fill="transparent"
                        initial={{ strokeDashoffset: circumference }}
                        r={radius}
                        stroke="currentColor"
                        strokeDasharray={circumference}
                        strokeLinecap="round"
                        strokeWidth="8"
                        transition={{ duration: 1.2, ease: "easeOut" }}
                    />
                </svg>
                <div className="absolute inset-0 flex items-center justify-center">
                    <span className={`text-lg font-bold ${colorClass}`}>{percentage}%</span>
                </div>
            </div>
            <div>
                <p className="text-sm font-semibold text-white">Win Ratio</p>
                <p className="text-xs text-gray-400">Backtest Complete</p>
            </div>
        </div>
    );
};

const ConditionsReportView: React.FC<{ report: StrategyReport }> = ({ report }) => (
    <div className="bg-[#191919] p-5 rounded-md border border-gray-600 overflow-y-auto h-[400px]">
        <h3 className="text-lg font-semibold text-white mb-3">Market Analysis Overview</h3>
        <p className="text-sm text-gray-300 leading-relaxed mb-6">{report.overview}</p>
        <h3 className="text-lg font-semibold text-white mb-3">Recommended Technical Strategy</h3>
        <div className="mb-6">
            <table className="w-full text-sm text-left">
                <thead className="border-b border-gray-700/50">
                <tr>
                    <th className="pb-3 pr-4 font-medium text-gray-400" scope="col">Component</th>
                    <th className="pb-3 pr-4 font-medium text-gray-400" scope="col">Indicator/condition</th>
                </tr>
                </thead>
                <tbody>
                {report.strategy.map((item, index) => (
                    <tr key={index} className="border-b border-gray-800/50 hover:bg-gray-800/30 transition-colors">
                        <td className="py-3 pr-4 font-medium text-white">{item.component}</td>
                        <td className="py-3 pr-4 text-gray-300">{item.indicator}</td>
                    </tr>
                ))}
                </tbody>
            </table>
        </div>
        <h3 className="text-lg font-semibold text-white mb-3">Technical Execution Logic</h3>
        <p className="text-sm text-gray-300 leading-relaxed">{report.execution}</p>
    </div>
);

// =====================================================================
// --- MAIN COMPONENT ---
// =====================================================================

export default function AIStrategyGenerator() {
    const [selectedAI, setSelectedAI] = useState(AI_MODELS[0].name);
    const [prompt, setPrompt] = useState('Create a strategy that buys when the 50 EMA crosses the 200 EMA (Golden Cross) and RSI (14) is above 50.');
    const [activeTab, setActiveTab] = useState(OUTPUT_TABS[0]);
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatedStrategy, setGeneratedStrategy] = useState<GeneratedStrategy | null>(null);
    const [isTesting, setIsTesting] = useState(false);
    const [testResults, setTestResults] = useState<{ winRatio: number } | null>(null);
    const [errorMessage, setErrorMessage] = useState<string | null>(null);

    const handleGenerate = useCallback(async () => {
        if (!prompt.trim() || isGenerating) return;
        setIsGenerating(true);
        setGeneratedStrategy(null);
        setErrorMessage(null);
        setTestResults(null);
        try {
            const strategy = await simulateAIGeneration(prompt, selectedAI);

            setGeneratedStrategy(strategy);
            setActiveTab(OUTPUT_TABS[0]);
        } catch {
            setErrorMessage("AI generation failed. Please refine your prompt and try again.");
        } finally {
            setIsGenerating(false);
        }
    }, [prompt, selectedAI, isGenerating]);

    const handleTestStrategy = useCallback(async () => {
        if (!generatedStrategy || isTesting) return;
        setIsTesting(true);
        setTestResults(null);
        setErrorMessage(null);
        try {
            const results = await simulateBacktest(generatedStrategy.code);

            setTestResults(results);
        } catch {
            setErrorMessage("Backtesting failed. Please review the strategy code for errors.");
        } finally {
            setIsTesting(false);
        }
    }, [generatedStrategy, isTesting]);

    const handleCodeChange = (newCode: string) => {
        setGeneratedStrategy(prev => prev ? ({ ...prev, code: newCode }) : null);
        setTestResults(null);
    };

    return (
        <div className="bg-dark-gray text-white px-8 pt-8 pb-3 rounded-xl shadow-2xl w-full max-w-5xl mx-auto h-full">
            <div className="flex justify-between items-center mb-6">
                <h2 className="text-2xl font-semibold text-gray-100">AI Strategy Generator</h2>
            </div>

            <div className="flex items-start gap-6 mb-6">
                <div className="flex-[2]">
                    <label className="block text-sm font-medium text-gray-400 mb-2" htmlFor="prompt">
                        Describe Your Strategy (Prompt) or Paste Code
                    </label>
                    <textarea
                        className="w-full bg-[#191919] border border-gray-600 text-white rounded-md px-3 py-2 text-sm focus:ring-1 focus:ring-blue-500/50 focus:border-blue-500 focus:outline-none resize-none"
                        id="prompt"
                        placeholder="e.g., Create a mean reversion strategy for BTC/USDT on the 1H timeframe..."
                        rows={5}
                        value={prompt}
                        onChange={(e) => setPrompt(e.target.value)}
                    />
                </div>
                <div className="flex-1 flex flex-col h-full">
                    <div>
                        <Combobox
                            label="Select AI Model"
                            options={AI_MODELS}
                            selected={selectedAI}
                            setSelected={(v) => setSelectedAI(v)}
                        />
                    </div>
                    <div className="mt-auto pt-10">
                        <button
                            className="w-full py-2.5 text-sm font-semibold text-white bg-blue-600 hover:bg-blue-700 rounded-md transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center"
                            disabled={!prompt.trim() || isGenerating}
                            onClick={handleGenerate}
                        >
                            {isGenerating ? "Generating..." : "Generate Strategy"}
                        </button>
                    </div>
                </div>
            </div>

            <AnimatePresence>
                {errorMessage && (
                    <motion.div animate={{ opacity: 1 }} className="mb-6 p-4 bg-red-500/20 border border-red-700 text-red-400 rounded-md text-sm" exit={{ opacity: 0 }} initial={{ opacity: 0 }}>
                        {errorMessage}
                    </motion.div>
                )}
            </AnimatePresence>

            <div className="flex-1 flex flex-col min-h-0">
                {isGenerating ? (
                    <SkeletonLoader />
                ) : generatedStrategy ? (
                    <motion.div animate={{ opacity: 1 }} className="flex flex-col gap-y-4 pt-3 flex-1" initial={{ opacity: 0 }} transition={{ duration: 0.3 }}>
                        <ResultTabs activeTab={activeTab} setActiveTab={setActiveTab} tabs={OUTPUT_TABS} />
                        <div className="flex-1 mt-4">
                            <AnimatePresence mode="wait">
                                {activeTab === 'Strategy Code' ? (
                                    <motion.div key="code" animate={{ opacity: 1 }} exit={{ opacity: 0 }} initial={{ opacity: 0 }} transition={{ duration: 0.2 }}>
                                        <textarea
                                            className="custom-code-editor w-full"
                                            value={generatedStrategy.code}
                                            onChange={(e) => handleCodeChange(e.target.value)}
                                        />
                                    </motion.div>
                                ) : (
                                    <motion.div key="conditions" animate={{ opacity: 1 }} exit={{ opacity: 0 }} initial={{ opacity: 0 }} transition={{ duration: 0.2 }}>
                                        <ConditionsReportView report={generatedStrategy.report} />
                                    </motion.div>
                                )}
                            </AnimatePresence>
                        </div>
                        <div className="flex items-start justify-between pt-4 mt-[-8px]">
                            <div className="flex-1 min-h-[88px] flex items-start mt-[-15px]">
                                <AnimatePresence>
                                    {testResults && (
                                        <motion.div animate={{ opacity: 1, scale: 1 }} initial={{ opacity: 0, scale: 0.9 }} transition={{ type: 'spring', stiffness: 300, damping: 20 }}>
                                            <WinRatioGauge ratio={testResults.winRatio} />
                                        </motion.div>
                                    )}
                                </AnimatePresence>
                            </div>
                            <div className="flex items-center space-x-4">
                                <button
                                    className="px-6 py-2 text-sm font-semibold text-white ai-bg shadow-lg rounded-full transition-all disabled:opacity-50 flex items-center justify-center"
                                    disabled={isTesting}
                                    onClick={handleTestStrategy}
                                >
                                    {isTesting ? <><Spinner className="mr-2 h-4 w-4" /> Testing...</> : "Test Strategy"}
                                </button>
                                <button
                                    className="px-8 py-2 text-sm font-semibold text-black bg-white hover:bg-gray-200 rounded-full transition-colors disabled:bg-gray-500 disabled:text-gray-800 disabled:cursor-not-allowed"
                                    disabled={!generatedStrategy || !testResults}
                                >
                                    Add Indicator
                                </button>
                            </div>
                        </div>
                    </motion.div>
                ) : (
                    <div className="pt-3 flex flex-col items-center justify-center h-full min-h-[400px]">
                        <div className="text-center">
                            <h1 className="text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-500 to-violet-500 animated-gradient mb-2">
                                Hello Max!
                            </h1>
                            <p className="text-gray-400">How can I help you create a strategy today?</p>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};
