const fs = require('fs');
const path = require('path');
const logger = require("../logs/logger");

/**
 * Loads a dynamic strategy class from a string of code.
 * It writes the code to a temporary file in the strategies/technical directory
 * so that `require('./BaseIndicator')` resolves correctly.
 * @param {string} strategyId - The unique ID (usually N8nJobResponse _id).
 * @param {string} codeString - The raw JavaScript code string from the DB.
 * @returns {Class} The instantiated Strategy Class.
 */
function loadDynamicStrategy(strategyId, codeString) {
    // Target directory: app/strategies/technical
    // This ensures require('./BaseIndicator') inside the generated code works.
    const strategyDir = path.join(__dirname, '../app/strategies/technical');

    // Create filename based on ID to avoid collisions
    const filename = `Dynamic_${strategyId}.js`;
    const filePath = path.join(strategyDir, filename);

    try {
        // 1. Write the file to disk
        // We add a comment at the top to indicate it's auto-generated
        const fileContent = `// AUTO-GENERATED BY N8N JOB ${strategyId}\n${codeString}`;
        fs.writeFileSync(filePath, fileContent, 'utf8');

        // 2. Clear Node's require cache (Crucial for hot-reloading/updates)
        if (require.cache[require.resolve(filePath)]) {
            delete require.cache[require.resolve(filePath)];
        }

        // 3. Require the class
        const StrategyClass = require(filePath);

        // Optional: Unlink (delete) file after loading to keep folders clean.
        // keeping it is often better for debugging.
        // fs.unlinkSync(filePath);

        return StrategyClass;
    } catch (err) {
        logger.error(`[StrategyLoader] Error loading strategy ${strategyId}:`, err);
        console.error(`[StrategyLoader] Error loading strategy ${strategyId}:`, err);
        throw new Error(`Failed to load dynamic strategy: ${err.message}`);
    }
}

module.exports = { loadDynamicStrategy };
