import {
    AdvancedConfigIllustrationIcon, AIEngineIllustrationIcon,
    AlgoTradingIllustrationIcon,
    BacktestIllustrationIcon,
    BrokerIllustrationIcon, CapitalAllocationIllustrationIcon,
    CapstoneIllustration, CommunityBotsIllustration, CreatorsHubIllustrationIcon, CustomPrecisionIllustration,
    DCAIllustrationIcon,
    DynamicStrategiesIllustration,
    EntriesThatWorkIllustrationIcon, FavoriteAIStrategyIllustrationIcon, GridBotsIllustrationIcon,
    GuardrailsIllustrationIcon, HumanInTheLoopIllustrationIcon,
    InsideAIEngineIllustrationIcon, OptimizationMethodsIllustration, PromptToStrategyIllustrationIcon,
    RegimeDetectionIllustration, SignalEnginesIllustration, TakingProfitIllustrationIcon,
    VolatilityFiltersIllustrationIcon,
    WelcomeIllustrationIcon
} from "@/utils/icons";

export const topicIcons = {
    welcome: WelcomeIllustrationIcon,
    algo: AlgoTradingIllustrationIcon,
    backtest: BacktestIllustrationIcon,
    broker: BrokerIllustrationIcon,
    creators: CreatorsHubIllustrationIcon,
    config: AdvancedConfigIllustrationIcon,
    ai: AIEngineIllustrationIcon,
    signal: SignalEnginesIllustration,
    precision: CustomPrecisionIllustration,
    dynamic: DynamicStrategiesIllustration,
    optimization: OptimizationMethodsIllustration,
    regime: RegimeDetectionIllustration,
    community: CommunityBotsIllustration,
    capstone: CapstoneIllustration,
    dca: DCAIllustrationIcon,
    grid: GridBotsIllustrationIcon,
    allocation: CapitalAllocationIllustrationIcon,
    entries: EntriesThatWorkIllustrationIcon,
    takeprofit: TakingProfitIllustrationIcon,
    volatility: VolatilityFiltersIllustrationIcon,
    insideAI: InsideAIEngineIllustrationIcon,
    promptToStrategy: PromptToStrategyIllustrationIcon,
    favoriteAI: FavoriteAIStrategyIllustrationIcon,
    guardrails: GuardrailsIllustrationIcon,
    humanInTheLoop: HumanInTheLoopIllustrationIcon,
};
