// models/Bot.js

const mongoose = require('mongoose');
const { Schema } = mongoose;

/**
 * strategyParamsSchema:
 * Contains parameters for technical indicators (e.g., RSI period, MACD periods, etc.).
 */
const strategyParamsSchema = new Schema({
    shortPeriod: { type: Number, min: 1 },   // For indicators like MA_Crossover, MACD
    longPeriod: { type: Number, min: 1 },      // For indicators like MA_Crossover, MACD
    period: { type: Number },                  // For RSI (e.g., 14)
    overbought: { type: Number },              // For RSI
    oversold: { type: Number },                // For RSI
}, { _id: false });

/**
 * riskParamsSchema:
 * Contains risk/money management parameters:
 * - positionSizingMethod: 'compound' or 'simple'.
 * - For compound: riskFraction (fraction of balance to risk) and stopLossDistance.
 * - For simple: positionSizeType ('percentage' or 'fixed') and positionSizeValue.
 * - maxOpenTrades: Maximum allowed open trades.
 */
const riskParamsSchema = new Schema({
    maxDrawdown: { type: Number },
    dailyLossLimit: { type: Number },
    positionSizingMethod: { type: String, enum: ['compound', 'simple'] },
    // Compound method parameters:
    riskFraction: { type: Number },
    stopLossDistance: { type: Number },
    // Simple method parameters:
    positionSizeType: { type: String, enum: ['percentage', 'fixed'] },
    positionSizeValue: { type: Number },
    maxOpenTrades: { type: Number }
}, { _id: false });

/**
 * marketInfoSchema:
 * Contains market-related information:
 * - Funds allocation (baseFund, tradeFund).
 * - Last finalized candle data.
 * - Current (live) candle price.
 * - Last signal generated by the indicator.
 */
const marketInfoSchema = new Schema({
    state: { type: String, default: 'inactive' },
    baseFund: { type: Number, default: 0 },
    tradeFund: { type: Number, default: 0 },
    // Stores the most recent complete candle.
    lastCandle: {
        timestamp: { type: Date },
        open: { type: Number },
        high: { type: Number },
        low: { type: Number },
        close: { type: Number },
        volume: { type: Number }
    },
    // Stores the live current candle's price.
    currentCandle: {
        price: { type: Number }
    },
    lastSignal: { type: String, default: 'HOLD' }
}, { _id: false });

/**
 * tradeInfoSchema:
 * Contains trade configuration settings including TP/SL levels,
 * leverage, and additional trade metrics.
 */
const tradeInfoSchema = new Schema({
    takeProfit: { type: Number },
    stopLoss: { type: Number },
    leverage: { type: Number },
    side: { type: String, enum: ['buy', 'sell'] },
    positionSide: { type: String, enum: ['long', 'short'] },
    winProbability: { type: Number },
    payoffRatio: { type: Number },
    lastTradeOutcome: { type: String }, // e.g., "win" or "loss"
    positionSizingMethod: { type: String, enum: ['compound', 'simple'] },
    tradingStrategy: { type: String, enum: ['default', 'optimized', 'dynamic'] },
    optimizationMethod: { type: String, enum: ['grid', 'bayesian', 'ann'] },
    minimumTrade: { type: Number },
    minimumWinRatio: { type: Number },
    minimumAccuracy: { type: Number },
    configId: { type: String },
    signalProcessingMethod: { type: String, enum: ['weighted', 'consensus'] }
}, { _id: false });

/**
 * botSchema:
 * The main schema for bots. This combines basic bot settings (name, symbol, timeframe),
 * indicator and risk strategy configuration, market and trade information,
 * user association, and additional bot-level risk management fields.
 */
const botSchema = new Schema({
    // Basic Information
    name: { type: String, required: true },
    symbol: {
        type: String,
        required: true,
        // Ensure symbol is in the format "BASE/QUOTE", e.g., "BTC/USDT".
        match: [/^[A-Z]+\/[A-Z]+$/, 'Use format: BASE/QUOTE (e.g. BTC/USDT)']
    },
    timeframe: {
        type: String,
        // Allowed timeframes.
        enum: ['1m', '5m', '15m', '30m', '1h', '4h', '1d', '1w'],
        required: true
    },
    // Indicator: The technical indicator used (e.g., "RSI", "MACD", "MA_Crossover", etc.).
    indicator: { type: String, required: true },
    // Risk Strategy: The money management strategy (e.g., "KellyCriterionStrategy", "MartingaleStrategy", etc.).
    riskStrategy: { type: String, required: true },
    // Strategy: Overall trading strategy. This can sometimes mirror the indicator, or combine both approaches.
    strategy: {
        type: String,
        enum: ['MA_Crossover', 'RSI', 'MACD', 'Martingale', 'MirroredMartingale', 'KellyCriterion', 'SimpleStrategy'],
        required: true
    },
    // Indicator-specific configuration parameters.
    strategyParams: strategyParamsSchema,
    // Risk management parameters.
    riskParams: riskParamsSchema,
    // Market information including funds allocation and candle data.
    marketInfo: marketInfoSchema,
    // Trade-related configuration.
    tradeInfo: tradeInfoSchema,
    // User association.
    userId: { type: Schema.Types.ObjectId, ref: 'User' },
    // Bot configuration fields.
    botType: { type: String, enum: ['indicator', 'grid', 'DCA'] },
    positionMode: { type: String, enum: ['hedge', 'single'] },
    fundMode: { type: String, enum: ['isolated', 'cross'] },
    userLevel: { type: Number, default: 1 },
    // Operational flags.
    active: { type: Boolean, default: false },
    mode: { type: String, enum: ['live', 'paper'], default: 'paper' },
    paperBalance: { type: Number, default: 10000 },
    // Bot-level risk management:
    cumulativePnL: { type: Number, default: 0 }, // Total profit/loss accumulated by the bot.
    botTP: { type: Number, default: 0 },           // Bot-level take profit threshold (stop trading if reached).
    botSL: { type: Number, default: 0 }            // Bot-level stop loss threshold (stop trading if reached).
}, { timestamps: true });

// Compound index to prevent duplicate bots for the same symbol, timeframe, and strategy.
botSchema.index({ symbol: 1, timeframe: 1, strategy: 1 }, { unique: true });

module.exports = mongoose.model('Bot', botSchema);
