// models/Bot.js

const mongoose = require('mongoose');
const { Schema } = mongoose;

/**
 * strategyParamsSchema:
 * Contains parameters for technical indicators (e.g., RSI period, MACD periods, etc.).
 */
const strategyParamsSchema = new Schema({
    shortPeriod: { type: Number, min: 1 },   // For indicators like MA_Crossover, MACD
    longPeriod: { type: Number, min: 1 },      // For indicators like MA_Crossover, MACD
    period: { type: Number },                  // For RSI (e.g., 14)
    overbought: { type: Number },              // For RSI
    oversold: { type: Number },                // For RSI
}, { _id: false });

/**
 * riskParamsSchema:
 * Contains risk/money management parameters:
 * - positionSizingMethod: 'compound' or 'simple'.
 * - For compound: riskFraction (fraction of balance to risk) and stopLossDistance.
 * - For simple: positionSizeType ('percentage' or 'fixed') and positionSizeValue.
 * - maxOpenTrades: Maximum allowed open trades.
 */
const riskParamsSchema = new Schema({
    maxDrawdown: { type: Number },
    dailyLossLimit: { type: Number },
    positionSizingMethod: { type: String, enum: ['compound', 'simple'] },
    // Compound method parameters:
    riskFraction: { type: Number },
    stopLossDistance: { type: Number },
    // Simple method parameters:
    positionSizeType: { type: String, enum: ['percentage', 'fixed'] },
    positionSizeValue: { type: Number },
    maxOpenTrades: { type: Number }
}, { _id: false });

/**
 * marketInfoSchema:
 * Contains market-related information:
 * - Funds allocation (baseFund, tradeFund) used for trading.
 * - Last finalized candle data.
 * - Current (live) candle price.
 * - Last signal generated by the indicator.
 */
const marketInfoSchema = new Schema({
    state: { type: String, default: 'inactive' },
    // Updated defaults: new bots will have a base fund of $10,000 and a trade fund of 50% if not provided.
    baseFund: { type: Number, default: 10000 },
    tradeFund: { type: Number, default: 50 },
    lastCandle: {
        timestamp: { type: Date },
        open: { type: Number },
        high: { type: Number },
        low: { type: Number },
        close: { type: Number },
        volume: { type: Number }
    },
    // Current live candle price.
    currentCandle: {
        price: { type: Number }
    },
    // Last signal from the indicator (default is 'HOLD').
    lastSignal: { type: String, default: 'HOLD' }
}, { _id: false });

/**
 * tradeInfoSchema:
 * Contains trade configuration settings including TP/SL levels,
 * leverage, and additional trade metrics.
 */
const tradeInfoSchema = new Schema({
    takeProfit: { type: Number },
    stopLoss: { type: Number },
    // Added a default leverage of 1x.
    leverage: { type: Number, default: 1 },
    side: { type: String, enum: ['buy', 'sell'] },
    positionSide: { type: String, enum: ['long', 'short'] },
    winProbability: { type: Number },
    payoffRatio: { type: Number },
    lastTradeOutcome: { type: String }, // e.g., "win" or "loss"
    // This field duplicates riskParams.positionSizingMethod; you might decide to rely on one of them.
    positionSizingMethod: { type: String, enum: ['compound', 'simple'] },
    tradingStrategy: { type: String, enum: ['default', 'optimized', 'dynamic'] },
    optimizationMethod: { type: String, enum: ['grid', 'bayesian', 'ann'] },
    minimumTrade: { type: Number },
    minimumWinRatio: { type: Number },
    minimumAccuracy: { type: Number },
    configId: { type: String },
    signalProcessingMethod: { type: String, enum: ['weighted', 'consensus'] }
}, { _id: false });

/**
 * botSchema:
 * The main schema for bots.
 * Combines basic bot settings with nested configurations for indicators, risk management,
 * market data, trade configuration, user association, and bot-level risk controls.
 */
const botSchema = new Schema({
    // Basic Information
    name: { type: String, required: true },
    symbol: {
        type: String,
        required: true,
        // Ensure symbol is in the format "BASE/QUOTE" (e.g., "BTC/USDT").
        match: [/^[A-Z]+\/[A-Z]+$/, 'Use format: BASE/QUOTE (e.g. BTC/USDT)']
    },
    timeframe: {
        type: String,
        // Allowed timeframes.
        enum: ['1m', '5m', '15m', '30m', '1h', '4h', '1d', '1w'],
        required: true
    },
    indicator: { type: String, required: true },      // e.g., "RSI", "MACD", "MA_Crossover", etc.
    riskStrategy: { type: String, required: true },     // e.g., "KellyCriterionStrategy", "MartingaleStrategy", etc.
    strategy: {
        type: String,
        // Overall trading strategy. For now, this can mirror the indicator or combine multiple strategies.
        enum: ['MA_Crossover', 'RSI', 'MACD', 'Martingale', 'MirroredMartingale', 'KellyCriterion', 'SimpleStrategy'],
        required: true
    },
    strategyParams: strategyParamsSchema, // Indicator-specific parameters.
    riskParams: riskParamsSchema,           // Money management parameters.
    marketInfo: marketInfoSchema,           // Market information and candle data.
    tradeInfo: tradeInfoSchema,             // Trade configuration.
    userId: { type: Schema.Types.ObjectId, ref: 'User' },
    botType: { type: String, enum: ['indicator', 'grid', 'DCA'] },
    positionMode: { type: String, enum: ['hedge', 'single'] },
    fundMode: { type: String, enum: ['isolated', 'cross'] },
    userLevel: { type: Number, default: 1 },
    // Operational flags.
    active: { type: Boolean, default: false },
    mode: { type: String, enum: ['live', 'paper'], default: 'paper' },
    paperBalance: { type: Number, default: 10000 },
    // Bot-level risk management.
    cumulativePnL: { type: Number, default: 0 },
    botTP: { type: Number, default: 0 },  // Take profit threshold (if reached, bot stops trading).
    botSL: { type: Number, default: 0 }   // Stop loss threshold (if reached, bot stops trading).
}, { timestamps: true });

// Create a compound index to prevent duplicate bots for the same symbol, timeframe, and strategy.
botSchema.index({ symbol: 1, timeframe: 1, strategy: 1 }, { unique: true });

module.exports = mongoose.model('Bot', botSchema);
